import {
  type DemoCase,
  type DemoLead,
  type DemoLocation,
  type DemoMonitoringHit,
  type DemoNotification,
  type DemoTip,
  type DemoUser,
} from "@/lib/types";

const locations = {
  eastleigh: {
    id: "loc-eastleigh",
    label: "Eastleigh Section 1",
    address: "General Waruinge Street",
    city: "Nairobi",
    county: "Nairobi",
    country: "Kenya",
    latitude: -1.2758,
    longitude: 36.8502,
  },
  nairobiCbd: {
    id: "loc-nairobi-cbd",
    label: "Nairobi CBD",
    address: "Tom Mboya Street",
    city: "Nairobi",
    county: "Nairobi",
    country: "Kenya",
    latitude: -1.2833,
    longitude: 36.8219,
  },
  westlands: {
    id: "loc-westlands",
    label: "Westlands",
    address: "Ring Road Westlands",
    city: "Nairobi",
    county: "Nairobi",
    country: "Kenya",
    latitude: -1.2675,
    longitude: 36.8108,
  },
  thikaRoad: {
    id: "loc-thika-road",
    label: "Thika Road Mall",
    address: "TRM Drive",
    city: "Nairobi",
    county: "Nairobi",
    country: "Kenya",
    latitude: -1.2312,
    longitude: 36.8772,
  },
  syokimau: {
    id: "loc-syokimau",
    label: "Syokimau Station",
    address: "Mombasa Road Spur",
    city: "Nairobi",
    county: "Machakos",
    country: "Kenya",
    latitude: -1.3576,
    longitude: 36.9157,
  },
  oldTown: {
    id: "loc-old-town",
    label: "Old Town",
    address: "Mbarak Hinawy Road",
    city: "Mombasa",
    county: "Mombasa",
    country: "Kenya",
    latitude: -4.0524,
    longitude: 39.6731,
  },
  nyali: {
    id: "loc-nyali",
    label: "Nyali Centre",
    address: "Links Road",
    city: "Mombasa",
    county: "Mombasa",
    country: "Kenya",
    latitude: -4.0334,
    longitude: 39.6988,
  },
  diani: {
    id: "loc-diani",
    label: "Diani Beach Road",
    address: "Ukunda",
    city: "Kwale",
    county: "Kwale",
    country: "Kenya",
    latitude: -4.2803,
    longitude: 39.5942,
  },
  kisumuBusPark: {
    id: "loc-kisumu-bus-park",
    label: "Kisumu Bus Park",
    address: "Oginga Odinga Street",
    city: "Kisumu",
    county: "Kisumu",
    country: "Kenya",
    latitude: -0.1015,
    longitude: 34.7617,
  },
  milimani: {
    id: "loc-milimani",
    label: "Milimani",
    address: "Achieng Oneko Road",
    city: "Kisumu",
    county: "Kisumu",
    country: "Kenya",
    latitude: -0.0898,
    longitude: 34.7554,
  },
  kakamega: {
    id: "loc-kakamega",
    label: "Kakamega Bus Stage",
    address: "Kenyatta Avenue",
    city: "Kakamega",
    county: "Kakamega",
    country: "Kenya",
    latitude: 0.2827,
    longitude: 34.7519,
  },
  eldoretMarket: {
    id: "loc-eldoret-market",
    label: "Eldoret Main Market",
    address: "Uganda Road",
    city: "Eldoret",
    county: "Uasin Gishu",
    country: "Kenya",
    latitude: 0.5143,
    longitude: 35.2698,
  },
  eldoretTown: {
    id: "loc-eldoret-town",
    label: "Eldoret CBD",
    address: "Oloo Street",
    city: "Eldoret",
    county: "Uasin Gishu",
    country: "Kenya",
    latitude: 0.5204,
    longitude: 35.2699,
  },
  nakuruTown: {
    id: "loc-nakuru-town",
    label: "Nakuru Town East",
    address: "Kenyatta Avenue",
    city: "Nakuru",
    county: "Nakuru",
    country: "Kenya",
    latitude: -0.2833,
    longitude: 36.0667,
  },
  machakos: {
    id: "loc-machakos",
    label: "Machakos Bus Park",
    address: "Mwatu wa Ngoma Road",
    city: "Machakos",
    county: "Machakos",
    country: "Kenya",
    latitude: -1.5177,
    longitude: 37.2634,
  },
} satisfies Record<string, DemoLocation>;

const sharedPassword = "TraceLink!2026";

export const demoUsers: DemoUser[] = [
  {
    id: "user-admin-1",
    name: "Grace Wanjiku",
    email: "admin@tracelink.org",
    password: sharedPassword,
    role: "ADMIN",
    title: "Head of operations",
    organization: "TraceLink Response Desk",
    avatarUrl: "https://i.pravatar.cc/160?img=32",
    phone: "+254 700 111 229",
  },
  {
    id: "user-admin-2",
    name: "Samuel Otieno",
    email: "moderator@tracelink.org",
    password: sharedPassword,
    role: "MODERATOR",
    title: "Lead moderator",
    organization: "TraceLink Response Desk",
    avatarUrl: "https://i.pravatar.cc/160?img=58",
    phone: "+254 700 282 910",
  },
  {
    id: "user-admin-3",
    name: "Leah Kipkurui",
    email: "admin2@tracelink.org",
    password: sharedPassword,
    role: "ADMIN",
    title: "Platform security manager",
    organization: "TraceLink Response Desk",
    avatarUrl: "https://i.pravatar.cc/160?img=47",
    phone: "+254 700 775 441",
  },
  {
    id: "user-family-1",
    name: "Amelia Hassan",
    email: "amelia@family.tracelink.org",
    password: sharedPassword,
    role: "FAMILY",
    title: "Case owner",
    organization: "Family account",
    avatarUrl: "https://i.pravatar.cc/160?img=5",
    phone: "+254 722 601 300",
  },
  {
    id: "user-family-2",
    name: "Peter Mwangi",
    email: "peter@family.tracelink.org",
    password: sharedPassword,
    role: "FAMILY",
    title: "Case owner",
    organization: "Family account",
    avatarUrl: "https://i.pravatar.cc/160?img=68",
    phone: "+254 733 204 817",
  },
  {
    id: "user-family-3",
    name: "Janet Atieno",
    email: "janet@family.tracelink.org",
    password: sharedPassword,
    role: "FAMILY",
    title: "Case owner",
    organization: "Family account",
    avatarUrl: "https://i.pravatar.cc/160?img=23",
    phone: "+254 712 995 160",
  },
];

export const demoCases: DemoCase[] = [
  {
    id: "case-amina-hassan",
    slug: "amina-hassan-2026",
    fullName: "Amina Hassan",
    nickname: "Mina",
    age: 16,
    gender: "Female",
    status: "ACTIVE",
    privacyLevel: "PUBLIC",
    lastSeenAt: "2026-03-28T15:40:00.000Z",
    lastSeenLocation: locations.eastleigh,
    city: "Nairobi",
    county: "Nairobi",
    country: "Kenya",
    physicalDescription:
      "Height 5'3\", slim build, brown eyes, shoulder-length braided hair, usually wears a silver crescent pendant.",
    clothingDescription:
      "Black hoodie, light grey trousers, white sneakers, navy backpack with reflective strip.",
    distinguishingFeatures:
      "Small scar above the left eyebrow and henna pattern fading on the right hand.",
    summary:
      "Amina left tuition in Eastleigh and never arrived home. Family confirmed her phone went offline shortly after 18:30 local time.",
    emergencyContact: "Amelia Hassan · +254 722 601 300",
    policeReference: "OB 47/28/03/2026",
    consentGiven: true,
    ownerId: "user-family-1",
    ownerName: "Amelia Hassan",
    images: [
      {
        id: "case-amina-image-1",
        url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80",
        caption: "Primary case photo from February 2026",
        isPrimary: true,
      },
      {
        id: "case-amina-image-2",
        url: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df2?auto=format&fit=crop&w=1200&q=80",
        caption: "School event photo",
      },
      {
        id: "case-amina-image-3",
        url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=80",
        caption: "Weekend family photo",
      },
    ],
    updates: [
      {
        id: "update-amina-1",
        createdAt: "2026-03-28T18:20:00.000Z",
        title: "Case opened",
        body: "Initial report verified with family contact and Nairobi police reference.",
        visibility: "PUBLIC",
        actor: "Grace Wanjiku",
      },
      {
        id: "update-amina-2",
        createdAt: "2026-03-29T07:10:00.000Z",
        title: "Transit route reviewed",
        body: "Family shared regular matatu route and two probable drop-off points for community watch.",
        visibility: "LIMITED",
        actor: "Samuel Otieno",
      },
      {
        id: "update-amina-3",
        createdAt: "2026-04-02T12:35:00.000Z",
        title: "Public monitoring expanded",
        body: "Added nickname and school-uniform keywords to monitoring watchlist after a witness note.",
        visibility: "PUBLIC",
        actor: "Leah Kipkurui",
      },
    ],
    keywords: ["Amina Hassan", "Mina", "#Eastleigh", "Waruinge", "navy backpack"],
  },
  {
    id: "case-daniel-mwangi",
    slug: "daniel-mwangi-2026",
    fullName: "Daniel Mwangi",
    nickname: "Dan",
    age: 22,
    gender: "Male",
    status: "ACTIVE",
    privacyLevel: "PUBLIC",
    lastSeenAt: "2026-04-04T18:15:00.000Z",
    lastSeenLocation: locations.oldTown,
    city: "Mombasa",
    county: "Mombasa",
    country: "Kenya",
    physicalDescription:
      "Height 5'10\", athletic build, short hair, trimmed beard, brown eyes, speaks English and Swahili.",
    clothingDescription:
      "Olive overshirt, black T-shirt, faded jeans, brown leather bracelet, dark running shoes.",
    distinguishingFeatures:
      "Tattoo of a compass on right forearm and healed fracture mark on left wrist.",
    summary:
      "Daniel was last seen after leaving a friend near Old Town. He missed scheduled transport back to Nairobi and has not checked in since.",
    emergencyContact: "Peter Mwangi · +254 733 204 817",
    policeReference: "OB 19/05/04/2026",
    consentGiven: true,
    ownerId: "user-family-2",
    ownerName: "Peter Mwangi",
    images: [
      {
        id: "case-daniel-image-1",
        url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=80",
        caption: "Primary case photo from March 2026",
        isPrimary: true,
      },
      {
        id: "case-daniel-image-2",
        url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=80",
        caption: "Office portrait",
      },
      {
        id: "case-daniel-image-3",
        url: "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=1200&q=80",
        caption: "Weekend photo near the coast",
      },
    ],
    updates: [
      {
        id: "update-daniel-1",
        createdAt: "2026-04-04T20:05:00.000Z",
        title: "Case opened",
        body: "Family verification completed and public page published.",
        visibility: "PUBLIC",
        actor: "Grace Wanjiku",
      },
      {
        id: "update-daniel-2",
        createdAt: "2026-04-05T08:15:00.000Z",
        title: "Port corridor watchlist added",
        body: "Monitoring terms expanded to include ferry stage and Old Town place mentions.",
        visibility: "LIMITED",
        actor: "Samuel Otieno",
      },
      {
        id: "update-daniel-3",
        createdAt: "2026-04-08T06:45:00.000Z",
        title: "Community poster rollout",
        body: "Printable poster QR page shared with volunteers across Mombasa and Kilifi groups.",
        visibility: "PUBLIC",
        actor: "Leah Kipkurui",
      },
    ],
    keywords: ["Daniel Mwangi", "Dan", "Old Town", "ferry", "#Mombasa"],
  },
  {
    id: "case-faith-atieno",
    slug: "faith-atieno-2026",
    fullName: "Faith Atieno",
    nickname: "Fifi",
    age: 13,
    gender: "Female",
    status: "ACTIVE",
    privacyLevel: "PUBLIC",
    lastSeenAt: "2026-03-19T14:30:00.000Z",
    lastSeenLocation: locations.kisumuBusPark,
    city: "Kisumu",
    county: "Kisumu",
    country: "Kenya",
    physicalDescription:
      "Height 4'11\", slight build, dark braided hair with blue beads, bright smile, brown eyes.",
    clothingDescription:
      "Maroon school sweater, navy skirt, white socks, black shoes, carrying a pink folder.",
    distinguishingFeatures:
      "Gap between front teeth and a tiny birthmark on left cheek.",
    summary:
      "Faith was separated from a relative at Kisumu Bus Park while traveling from school. Family has received no direct contact since the incident.",
    emergencyContact: "Janet Atieno · +254 712 995 160",
    policeReference: "OB 08/19/03/2026",
    consentGiven: true,
    ownerId: "user-family-3",
    ownerName: "Janet Atieno",
    images: [
      {
        id: "case-faith-image-1",
        url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
        caption: "Primary case photo from school celebration",
        isPrimary: true,
      },
      {
        id: "case-faith-image-2",
        url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
        caption: "Portrait with braided hair and blue beads",
      },
      {
        id: "case-faith-image-3",
        url: "https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=1200&q=80",
        caption: "Family event picture",
      },
    ],
    updates: [
      {
        id: "update-faith-1",
        createdAt: "2026-03-19T17:25:00.000Z",
        title: "Case opened",
        body: "Guardian identity verified and school contact added to the file.",
        visibility: "PUBLIC",
        actor: "Grace Wanjiku",
      },
      {
        id: "update-faith-2",
        createdAt: "2026-03-21T11:20:00.000Z",
        title: "Bus corridor alerts issued",
        body: "Volunteer network alerted across Kisumu and Kakamega transport corridor.",
        visibility: "PUBLIC",
        actor: "Samuel Otieno",
      },
      {
        id: "update-faith-3",
        createdAt: "2026-03-25T09:30:00.000Z",
        title: "Witness note matched",
        body: "Unverified public report suggested a similar school sweater near Kakamega stage.",
        visibility: "LIMITED",
        actor: "Leah Kipkurui",
      },
    ],
    keywords: ["Faith Atieno", "Fifi", "Kisumu Bus Park", "pink folder", "#Kisumu"],
  },
  {
    id: "case-kelvin-kiptoo",
    slug: "kelvin-kiptoo-2026",
    fullName: "Kelvin Kiptoo",
    nickname: "Kelvo",
    age: 31,
    gender: "Male",
    status: "ACTIVE",
    privacyLevel: "LIMITED",
    lastSeenAt: "2026-04-08T03:50:00.000Z",
    lastSeenLocation: locations.eldoretMarket,
    city: "Eldoret",
    county: "Uasin Gishu",
    country: "Kenya",
    physicalDescription:
      "Height 6'0\", lean build, close-cut hair, wears thin metal glasses when reading.",
    clothingDescription:
      "Reflective blue work jacket, charcoal joggers, black cap, tan boots.",
    distinguishingFeatures:
      "Noticeable limp on the right leg after a previous injury.",
    summary:
      "Kelvin disappeared after an early-morning delivery run through Eldoret market. His vehicle was located later without him.",
    emergencyContact: "Peter Mwangi · +254 733 204 817",
    policeReference: "OB 13/08/04/2026",
    consentGiven: true,
    ownerId: "user-family-2",
    ownerName: "Peter Mwangi",
    images: [
      {
        id: "case-kelvin-image-1",
        url: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=1200&q=80",
        caption: "Primary case photo from February 2026",
        isPrimary: true,
      },
      {
        id: "case-kelvin-image-2",
        url: "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=1200&q=80",
        caption: "Casual outdoor photo",
      },
      {
        id: "case-kelvin-image-3",
        url: "https://images.unsplash.com/photo-1542178243-bc20204b769f?auto=format&fit=crop&w=1200&q=80",
        caption: "Team portrait with work jacket",
      },
    ],
    updates: [
      {
        id: "update-kelvin-1",
        createdAt: "2026-04-08T07:05:00.000Z",
        title: "Case opened",
        body: "Vehicle recovery location logged and restricted details shared with moderators.",
        visibility: "LIMITED",
        actor: "Grace Wanjiku",
      },
      {
        id: "update-kelvin-2",
        createdAt: "2026-04-09T09:50:00.000Z",
        title: "Market CCTV window added",
        body: "Investigators noted a probable route through two loading bays before signal loss.",
        visibility: "LIMITED",
        actor: "Samuel Otieno",
      },
      {
        id: "update-kelvin-3",
        createdAt: "2026-04-11T15:10:00.000Z",
        title: "Regional monitoring terms updated",
        body: "Work jacket color and limp descriptor added to place-based manual review queue.",
        visibility: "LIMITED",
        actor: "Leah Kipkurui",
      },
    ],
    keywords: ["Kelvin Kiptoo", "Kelvo", "reflective blue jacket", "Eldoret Market"],
  },
  {
    id: "case-ruth-njeri",
    slug: "ruth-njeri-2026",
    fullName: "Ruth Njeri",
    nickname: "Ruthie",
    age: 27,
    gender: "Female",
    status: "FOUND",
    privacyLevel: "LIMITED",
    lastSeenAt: "2026-04-10T05:10:00.000Z",
    lastSeenLocation: locations.thikaRoad,
    city: "Nairobi",
    county: "Nairobi",
    country: "Kenya",
    physicalDescription:
      "Height 5'6\", medium build, natural hair tied back, brown eyes, calm speaking voice.",
    clothingDescription:
      "Cream trench coat, dark blue blouse, black trousers, white trainers, brown crossbody bag.",
    distinguishingFeatures:
      "Silver nose stud and tiny heart tattoo near the left wrist.",
    summary:
      "Ruth was reported missing after leaving a bus terminus on Thika Road. The case is retained for audit and family reference after recovery.",
    emergencyContact: "Amelia Hassan · +254 722 601 300",
    policeReference: "OB 31/10/04/2026",
    consentGiven: true,
    ownerId: "user-family-1",
    ownerName: "Amelia Hassan",
    images: [
      {
        id: "case-ruth-image-1",
        url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1200&q=80",
        caption: "Primary case photo from January 2026",
        isPrimary: true,
      },
      {
        id: "case-ruth-image-2",
        url: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=1200&q=80",
        caption: "Professional portrait",
      },
      {
        id: "case-ruth-image-3",
        url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
        caption: "Weekend family photo",
      },
    ],
    updates: [
      {
        id: "update-ruth-1",
        createdAt: "2026-04-10T08:20:00.000Z",
        title: "Case opened",
        body: "Public page limited while transport CCTV was reviewed.",
        visibility: "LIMITED",
        actor: "Grace Wanjiku",
      },
      {
        id: "update-ruth-2",
        createdAt: "2026-04-10T14:45:00.000Z",
        title: "Lead escalated",
        body: "Multiple commuter sightings aligned around Syokimau corridor.",
        visibility: "LIMITED",
        actor: "Samuel Otieno",
      },
      {
        id: "update-ruth-3",
        createdAt: "2026-04-11T09:15:00.000Z",
        title: "Recovered safely",
        body: "Case status changed to found after family confirmation.",
        visibility: "PUBLIC",
        actor: "Leah Kipkurui",
      },
    ],
    keywords: ["Ruth Njeri", "Ruthie", "Thika Road", "cream trench coat", "#TRM"],
  },
];

export const demoTips: DemoTip[] = [
  {
    id: "tip-001",
    caseId: "case-amina-hassan",
    description:
      "Saw someone similar waiting near a matatu stage with a navy backpack around dusk.",
    seenAt: "2026-03-28T16:20:00.000Z",
    location: locations.nairobiCbd,
    reporterName: "Mary K.",
    reporterContact: "+254 711 002 117",
    anonymous: false,
    confidence: 0.64,
    status: "UNDER_REVIEW",
    similarityScore: 0.58,
    similarityNotes:
      "Possible similarity only. Needs manual comparison against case images.",
    createdAt: "2026-03-28T18:55:00.000Z",
  },
  {
    id: "tip-002",
    caseId: "case-amina-hassan",
    description:
      "A teenager matching the description asked for directions near Eastleigh social hall.",
    seenAt: "2026-03-29T08:35:00.000Z",
    location: locations.eastleigh,
    anonymous: true,
    confidence: 0.41,
    status: "NEW",
    createdAt: "2026-03-29T09:00:00.000Z",
  },
  {
    id: "tip-003",
    caseId: "case-amina-hassan",
    description:
      "Photo submitted from Westlands taxi bay. Clothing color is close but not exact.",
    seenAt: "2026-03-31T17:10:00.000Z",
    location: locations.westlands,
    reporterName: "David O.",
    anonymous: false,
    confidence: 0.53,
    status: "ESCALATED",
    similarityScore: 0.66,
    similarityNotes:
      "Hairline and necklace placement look similar under low light.",
    imageUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
    createdAt: "2026-03-31T17:26:00.000Z",
  },
  {
    id: "tip-004",
    caseId: "case-amina-hassan",
    description:
      "Community volunteer checked a boarding room lead and ruled it out.",
    seenAt: "2026-04-01T11:15:00.000Z",
    location: locations.syokimau,
    reporterName: "Volunteer desk",
    anonymous: false,
    confidence: 0.18,
    status: "DISMISSED",
    createdAt: "2026-04-01T12:02:00.000Z",
  },
  {
    id: "tip-005",
    caseId: "case-daniel-mwangi",
    description:
      "Saw a man matching Daniel's photo buying water close to ferry stage after 10 pm.",
    seenAt: "2026-04-04T19:18:00.000Z",
    location: locations.oldTown,
    anonymous: true,
    confidence: 0.61,
    status: "UNDER_REVIEW",
    createdAt: "2026-04-04T20:31:00.000Z",
  },
  {
    id: "tip-006",
    caseId: "case-daniel-mwangi",
    description:
      "He may have boarded a matatu heading toward Nyali with two other young men.",
    seenAt: "2026-04-05T05:50:00.000Z",
    location: locations.nyali,
    reporterName: "Ali B.",
    reporterContact: "+254 721 910 510",
    anonymous: false,
    confidence: 0.57,
    status: "VERIFIED",
    createdAt: "2026-04-05T06:10:00.000Z",
  },
  {
    id: "tip-007",
    caseId: "case-daniel-mwangi",
    description:
      "Submitted image from a coastal roadside kiosk. Bracelets look similar.",
    seenAt: "2026-04-06T09:25:00.000Z",
    location: locations.diani,
    reporterName: "Asha L.",
    anonymous: false,
    confidence: 0.48,
    status: "ESCALATED",
    similarityScore: 0.63,
    similarityNotes: "Forearm proportions match but visibility is limited.",
    imageUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
    createdAt: "2026-04-06T09:32:00.000Z",
  },
  {
    id: "tip-008",
    caseId: "case-daniel-mwangi",
    description:
      "Possible mention near the port area, but witness could not confirm the face.",
    seenAt: "2026-04-07T13:10:00.000Z",
    location: locations.oldTown,
    anonymous: true,
    confidence: 0.33,
    status: "NEW",
    createdAt: "2026-04-07T13:42:00.000Z",
  },
  {
    id: "tip-009",
    caseId: "case-faith-atieno",
    description:
      "School-age girl with blue beads was seen near Milimani asking for a stage name.",
    seenAt: "2026-03-20T08:35:00.000Z",
    location: locations.milimani,
    reporterName: "Hellen O.",
    reporterContact: "+254 718 550 901",
    anonymous: false,
    confidence: 0.72,
    status: "VERIFIED",
    createdAt: "2026-03-20T09:00:00.000Z",
  },
  {
    id: "tip-010",
    caseId: "case-faith-atieno",
    description:
      "Child in maroon sweater was seen boarding a vehicle toward Kakamega.",
    seenAt: "2026-03-21T06:20:00.000Z",
    location: locations.kakamega,
    anonymous: true,
    confidence: 0.54,
    status: "UNDER_REVIEW",
    createdAt: "2026-03-21T07:10:00.000Z",
  },
  {
    id: "tip-011",
    caseId: "case-faith-atieno",
    description: "Photo submitted by trader from Kakamega stage for manual review.",
    seenAt: "2026-03-22T13:05:00.000Z",
    location: locations.kakamega,
    reporterName: "Trader desk",
    anonymous: false,
    confidence: 0.47,
    status: "ESCALATED",
    similarityScore: 0.59,
    similarityNotes:
      "Uniform colors align, but facial detail is too limited for any conclusion.",
    imageUrl:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
    createdAt: "2026-03-22T13:40:00.000Z",
  },
  {
    id: "tip-012",
    caseId: "case-faith-atieno",
    description:
      "Walk-in report from volunteer did not match age or height after follow-up.",
    seenAt: "2026-03-23T10:10:00.000Z",
    location: locations.kisumuBusPark,
    reporterName: "Field volunteer",
    anonymous: false,
    confidence: 0.22,
    status: "DISMISSED",
    createdAt: "2026-03-23T11:05:00.000Z",
  },
  {
    id: "tip-013",
    caseId: "case-kelvin-kiptoo",
    description:
      "A man wearing a reflective blue jacket was seen resting near Eldoret town stage.",
    seenAt: "2026-04-08T10:45:00.000Z",
    location: locations.eldoretTown,
    reporterName: "Josphat K.",
    reporterContact: "+254 734 882 340",
    anonymous: false,
    confidence: 0.68,
    status: "UNDER_REVIEW",
    createdAt: "2026-04-08T11:10:00.000Z",
  },
  {
    id: "tip-014",
    caseId: "case-kelvin-kiptoo",
    description:
      "Kiosk owner thinks Kelvin asked for directions toward Nakuru buses.",
    seenAt: "2026-04-09T05:50:00.000Z",
    location: locations.nakuruTown,
    anonymous: true,
    confidence: 0.44,
    status: "NEW",
    createdAt: "2026-04-09T06:18:00.000Z",
  },
  {
    id: "tip-015",
    caseId: "case-kelvin-kiptoo",
    description:
      "Photo from market rear gate shows similar jacket and limp pattern.",
    seenAt: "2026-04-09T08:15:00.000Z",
    location: locations.eldoretMarket,
    reporterName: "Market watch",
    anonymous: false,
    confidence: 0.63,
    status: "ESCALATED",
    similarityScore: 0.71,
    similarityNotes:
      "Stride asymmetry looks consistent with case description.",
    imageUrl:
      "https://images.unsplash.com/photo-1542178243-bc20204b769f?auto=format&fit=crop&w=900&q=80",
    createdAt: "2026-04-09T08:26:00.000Z",
  },
  {
    id: "tip-016",
    caseId: "case-kelvin-kiptoo",
    description:
      "Unconfirmed late-night sighting from long-distance driver on highway route.",
    seenAt: "2026-04-10T22:20:00.000Z",
    location: locations.nakuruTown,
    anonymous: true,
    confidence: 0.29,
    status: "NEW",
    createdAt: "2026-04-10T22:45:00.000Z",
  },
  {
    id: "tip-017",
    caseId: "case-ruth-njeri",
    description:
      "Woman resembling Ruth boarded a train from Syokimau and appeared distressed.",
    seenAt: "2026-04-10T06:40:00.000Z",
    location: locations.syokimau,
    reporterName: "Commuter relay",
    anonymous: false,
    confidence: 0.77,
    status: "VERIFIED",
    createdAt: "2026-04-10T07:05:00.000Z",
  },
  {
    id: "tip-018",
    caseId: "case-ruth-njeri",
    description: "Security desk shared CCTV still from station waiting area.",
    seenAt: "2026-04-10T07:10:00.000Z",
    location: locations.syokimau,
    reporterName: "Station security",
    anonymous: false,
    confidence: 0.82,
    status: "VERIFIED",
    similarityScore: 0.74,
    similarityNotes:
      "Strong clothing and facial structure match. Still not treated as identity confirmation.",
    imageUrl:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80",
    createdAt: "2026-04-10T07:18:00.000Z",
  },
  {
    id: "tip-019",
    caseId: "case-ruth-njeri",
    description:
      "Brief report from Thika Road Mall was later tied to the same travel corridor.",
    seenAt: "2026-04-10T05:25:00.000Z",
    location: locations.thikaRoad,
    anonymous: true,
    confidence: 0.49,
    status: "VERIFIED",
    createdAt: "2026-04-10T05:50:00.000Z",
  },
  {
    id: "tip-020",
    caseId: "case-daniel-mwangi",
    description:
      "Anonymous caller mentioned a man with a compass tattoo near coastal coach parking.",
    seenAt: "2026-04-08T18:10:00.000Z",
    location: locations.nyali,
    anonymous: true,
    confidence: 0.52,
    status: "UNDER_REVIEW",
    createdAt: "2026-04-08T18:21:00.000Z",
  },
];

export const demoMonitoringHits: DemoMonitoringHit[] = [
  {
    id: "hit-001",
    caseId: "case-amina-hassan",
    source: "X",
    sourceLabel: "X",
    query: "Amina Hassan OR Mina Eastleigh",
    textSnippet:
      "Anyone know this girl with a navy backpack near Eastleigh social hall around sunset?",
    handle: "@nairobivolunteer",
    url: "https://example.org/monitoring/x/1",
    timestamp: "2026-03-29T06:45:00.000Z",
    location: locations.eastleigh,
    confidenceScore: 0.61,
    reviewStatus: "UNDER_REVIEW",
  },
  {
    id: "hit-002",
    caseId: "case-amina-hassan",
    source: "WEB",
    sourceLabel: "Community forum",
    query: "navy backpack Waruinge",
    textSnippet:
      "Late-night post asking whether a teenager needed help near Waruinge Street.",
    url: "https://example.org/monitoring/web/2",
    timestamp: "2026-03-30T19:10:00.000Z",
    location: locations.eastleigh,
    confidenceScore: 0.52,
    reviewStatus: "NEW",
  },
  {
    id: "hit-003",
    caseId: "case-amina-hassan",
    source: "INSTAGRAM",
    sourceLabel: "Instagram",
    query: "#Eastleigh #Mina",
    textSnippet:
      "Short story clip from a taxi rank showing a girl with similar profile and white sneakers.",
    handle: "@eastleigh_live",
    url: "https://example.org/monitoring/ig/3",
    timestamp: "2026-03-31T16:58:00.000Z",
    location: locations.nairobiCbd,
    mediaThumbnailUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80",
    confidenceScore: 0.67,
    reviewStatus: "ESCALATED",
  },
  {
    id: "hit-004",
    caseId: "case-daniel-mwangi",
    source: "FACEBOOK",
    sourceLabel: "Facebook",
    query: "Daniel Mwangi Old Town",
    textSnippet:
      "Post asking whether a Nairobi visitor lost contact after leaving Old Town late Friday.",
    handle: "Mombasa Watch",
    url: "https://example.org/monitoring/fb/4",
    timestamp: "2026-04-05T04:40:00.000Z",
    location: locations.oldTown,
    confidenceScore: 0.56,
    reviewStatus: "UNDER_REVIEW",
  },
  {
    id: "hit-005",
    caseId: "case-daniel-mwangi",
    source: "X",
    sourceLabel: "X",
    query: "compass tattoo ferry stage",
    textSnippet:
      "Spotted a traveler asking for Nairobi coach options, had a compass tattoo on forearm.",
    handle: "@coastalert",
    url: "https://example.org/monitoring/x/5",
    timestamp: "2026-04-05T19:25:00.000Z",
    location: locations.oldTown,
    confidenceScore: 0.73,
    reviewStatus: "ESCALATED",
  },
  {
    id: "hit-006",
    caseId: "case-daniel-mwangi",
    source: "WEB",
    sourceLabel: "Travel board",
    query: "Dan Nyali coach",
    textSnippet:
      "Short post about a quiet man in an olive overshirt waiting at Nyali coach parking.",
    url: "https://example.org/monitoring/web/6",
    timestamp: "2026-04-06T12:45:00.000Z",
    location: locations.nyali,
    confidenceScore: 0.49,
    reviewStatus: "NEW",
  },
  {
    id: "hit-007",
    caseId: "case-faith-atieno",
    source: "FACEBOOK",
    sourceLabel: "Facebook",
    query: "girl blue beads Kisumu bus park",
    textSnippet:
      "Community group post describing a school-age girl asking for a Kakamega route.",
    handle: "Kisumu Community Desk",
    url: "https://example.org/monitoring/fb/7",
    timestamp: "2026-03-20T08:10:00.000Z",
    location: locations.kisumuBusPark,
    confidenceScore: 0.74,
    reviewStatus: "APPROVED",
  },
  {
    id: "hit-008",
    caseId: "case-faith-atieno",
    source: "INSTAGRAM",
    sourceLabel: "Instagram",
    query: "#Kisumu #schoolgirl",
    textSnippet:
      "Market clip includes a maroon sweater and pink folder in the background.",
    handle: "@kisumu_street_view",
    url: "https://example.org/monitoring/ig/8",
    timestamp: "2026-03-21T10:22:00.000Z",
    location: locations.milimani,
    mediaThumbnailUrl:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80",
    confidenceScore: 0.58,
    reviewStatus: "UNDER_REVIEW",
  },
  {
    id: "hit-009",
    caseId: "case-faith-atieno",
    source: "MANUAL",
    sourceLabel: "Manual import",
    query: "Kakamega stage volunteer note",
    textSnippet:
      "Volunteer imported note about a child with blue beads waiting near stage kiosks.",
    url: "https://example.org/monitoring/manual/9",
    timestamp: "2026-03-22T15:05:00.000Z",
    location: locations.kakamega,
    confidenceScore: 0.62,
    reviewStatus: "ESCALATED",
  },
  {
    id: "hit-010",
    caseId: "case-kelvin-kiptoo",
    source: "X",
    sourceLabel: "X",
    query: "reflective blue jacket Eldoret",
    textSnippet:
      "Someone matching that jacket was seen limping near a loading bay before sunrise.",
    handle: "@eldoretwatch",
    url: "https://example.org/monitoring/x/10",
    timestamp: "2026-04-08T05:05:00.000Z",
    location: locations.eldoretMarket,
    confidenceScore: 0.69,
    reviewStatus: "ESCALATED",
  },
  {
    id: "hit-011",
    caseId: "case-kelvin-kiptoo",
    source: "WEB",
    sourceLabel: "Regional bulletin",
    query: "Kelvo Nakuru route",
    textSnippet:
      "Driver bulletin mentions a passenger with a limp asking for long-distance fares.",
    url: "https://example.org/monitoring/web/11",
    timestamp: "2026-04-09T07:05:00.000Z",
    location: locations.nakuruTown,
    confidenceScore: 0.46,
    reviewStatus: "UNDER_REVIEW",
  },
  {
    id: "hit-012",
    caseId: "case-kelvin-kiptoo",
    source: "MANUAL",
    sourceLabel: "Manual import",
    query: "market gate still frame",
    textSnippet:
      "Imported still image from volunteer with similar jacket and right-leg gait pattern.",
    url: "https://example.org/monitoring/manual/12",
    timestamp: "2026-04-09T08:30:00.000Z",
    location: locations.eldoretMarket,
    mediaThumbnailUrl:
      "https://images.unsplash.com/photo-1542178243-bc20204b769f?auto=format&fit=crop&w=800&q=80",
    confidenceScore: 0.76,
    reviewStatus: "ESCALATED",
  },
  {
    id: "hit-013",
    caseId: "case-ruth-njeri",
    source: "FACEBOOK",
    sourceLabel: "Facebook",
    query: "cream trench coat Syokimau",
    textSnippet:
      "Commuter post about a woman who appeared lost near Syokimau platform.",
    handle: "Nairobi Rail Community",
    url: "https://example.org/monitoring/fb/13",
    timestamp: "2026-04-10T06:52:00.000Z",
    location: locations.syokimau,
    confidenceScore: 0.81,
    reviewStatus: "APPROVED",
  },
  {
    id: "hit-014",
    caseId: "case-ruth-njeri",
    source: "X",
    sourceLabel: "X",
    query: "Ruthie train Syokimau",
    textSnippet:
      "Thread mentioned a woman matching the same outfit asking about town-bound departures.",
    handle: "@commuterline_ke",
    url: "https://example.org/monitoring/x/14",
    timestamp: "2026-04-10T07:05:00.000Z",
    location: locations.syokimau,
    confidenceScore: 0.65,
    reviewStatus: "APPROVED",
  },
  {
    id: "hit-015",
    caseId: "case-amina-hassan",
    source: "MANUAL",
    sourceLabel: "Manual import",
    query: "Eastleigh school route import",
    textSnippet:
      "Manual upload from volunteer noted a similar pendant and backpack at a junction kiosk.",
    url: "https://example.org/monitoring/manual/15",
    timestamp: "2026-04-02T11:25:00.000Z",
    location: locations.eastleigh,
    confidenceScore: 0.59,
    reviewStatus: "UNDER_REVIEW",
  },
];

export const demoLeads: DemoLead[] = [
  {
    id: "lead-001",
    caseId: "case-amina-hassan",
    title: "Westlands taxi bay image",
    snippet:
      "Tip image shows similar necklace placement and backpack profile.",
    source: "MANUAL",
    sourceLabel: "Public tip",
    confidenceScore: 0.66,
    similarityScore: 0.66,
    status: "ESCALATED",
    occurredAt: "2026-03-31T17:10:00.000Z",
    mediaThumbnailUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80",
    location: locations.westlands,
    notes:
      "Possible similarity only. Clothing mismatch remains unresolved. Moderator requested venue CCTV check.",
    audit: [
      {
        id: "audit-lead-001-1",
        at: "2026-03-31T17:40:00.000Z",
        actor: "Samuel Otieno",
        action: "Lead escalated",
        details: "Requested manual image comparison against all case photos.",
      },
    ],
  },
  {
    id: "lead-002",
    caseId: "case-daniel-mwangi",
    title: "Ferry-stage tattoo mention",
    snippet:
      "Public post described a traveler with a compass tattoo seeking coach options.",
    source: "X",
    sourceLabel: "X monitoring",
    confidenceScore: 0.73,
    status: "ESCALATED",
    occurredAt: "2026-04-05T19:25:00.000Z",
    handle: "@coastalert",
    url: "https://example.org/monitoring/x/5",
    location: locations.oldTown,
    notes:
      "High-value clue because of the tattoo descriptor and timing near the last-seen corridor.",
    audit: [
      {
        id: "audit-lead-002-1",
        at: "2026-04-05T20:10:00.000Z",
        actor: "Leah Kipkurui",
        action: "Lead approved for field follow-up",
        details: "Shared with family and coastal volunteer network.",
      },
    ],
  },
  {
    id: "lead-003",
    caseId: "case-daniel-mwangi",
    title: "Nyali coach parking sighting",
    snippet:
      "Witness and monitoring post both point to a man in an olive overshirt near coaches.",
    source: "WEB",
    sourceLabel: "Travel board",
    confidenceScore: 0.58,
    status: "UNDER_REVIEW",
    occurredAt: "2026-04-06T12:45:00.000Z",
    location: locations.nyali,
    notes:
      "Cross-reference underway against passenger manifests shared manually by partner volunteers.",
    audit: [
      {
        id: "audit-lead-003-1",
        at: "2026-04-06T13:15:00.000Z",
        actor: "Grace Wanjiku",
        action: "Lead queued",
        details: "Waiting on second corroborating source.",
      },
    ],
  },
  {
    id: "lead-004",
    caseId: "case-faith-atieno",
    title: "Kakamega stage school-sweater sighting",
    snippet:
      "Volunteer import and tip report both describe blue beads and a pink folder.",
    source: "MANUAL",
    sourceLabel: "Manual import",
    confidenceScore: 0.69,
    similarityScore: 0.59,
    status: "APPROVED",
    occurredAt: "2026-03-22T13:05:00.000Z",
    location: locations.kakamega,
    notes:
      "Lead kept active despite limited image clarity because multiple independent descriptors align.",
    audit: [
      {
        id: "audit-lead-004-1",
        at: "2026-03-22T15:20:00.000Z",
        actor: "Samuel Otieno",
        action: "Lead approved",
        details: "Volunteer search radius expanded across Kakamega stage.",
      },
    ],
  },
  {
    id: "lead-005",
    caseId: "case-kelvin-kiptoo",
    title: "Market gate still frame",
    snippet:
      "Manual still frame suggests matching jacket color and visible limp pattern.",
    source: "MANUAL",
    sourceLabel: "Manual import",
    confidenceScore: 0.76,
    similarityScore: 0.71,
    status: "ESCALATED",
    occurredAt: "2026-04-09T08:30:00.000Z",
    mediaThumbnailUrl:
      "https://images.unsplash.com/photo-1542178243-bc20204b769f?auto=format&fit=crop&w=800&q=80",
    location: locations.eldoretMarket,
    notes:
      "Possible similarity only. Movement pattern is stronger than facial detail. Moderator flagged for immediate field review.",
    audit: [
      {
        id: "audit-lead-005-1",
        at: "2026-04-09T08:40:00.000Z",
        actor: "Leah Kipkurui",
        action: "Lead escalated",
        details: "Sent to investigators and family owner for joint review.",
      },
    ],
  },
  {
    id: "lead-006",
    caseId: "case-kelvin-kiptoo",
    title: "Highway driver bulletin",
    snippet:
      "Regional bulletin mentions a passenger with a limp asking for Nakuru fares.",
    source: "WEB",
    sourceLabel: "Regional bulletin",
    confidenceScore: 0.46,
    status: "UNDER_REVIEW",
    occurredAt: "2026-04-09T07:05:00.000Z",
    location: locations.nakuruTown,
    notes:
      "Potential route change indicator. Needs a second corroborating signal before escalation.",
    audit: [
      {
        id: "audit-lead-006-1",
        at: "2026-04-09T07:40:00.000Z",
        actor: "Grace Wanjiku",
        action: "Lead queued",
        details: "Monitoring kept active on Nakuru transport channels.",
      },
    ],
  },
  {
    id: "lead-007",
    caseId: "case-ruth-njeri",
    title: "Syokimau station CCTV still",
    snippet:
      "Station desk still aligns strongly with Ruth's clothing and travel timeline.",
    source: "MANUAL",
    sourceLabel: "Security desk",
    confidenceScore: 0.82,
    similarityScore: 0.74,
    status: "APPROVED",
    occurredAt: "2026-04-10T07:10:00.000Z",
    mediaThumbnailUrl:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=800&q=80",
    location: locations.syokimau,
    notes:
      "Possible similarity only. Lead later contributed to safe recovery confirmation.",
    audit: [
      {
        id: "audit-lead-007-1",
        at: "2026-04-10T07:30:00.000Z",
        actor: "Samuel Otieno",
        action: "Lead approved",
        details: "Shared with rail security and family contact immediately.",
      },
    ],
  },
  {
    id: "lead-008",
    caseId: "case-amina-hassan",
    title: "Eastleigh kiosk volunteer import",
    snippet:
      "Pendant and backpack mention overlaps with family description.",
    source: "MANUAL",
    sourceLabel: "Volunteer import",
    confidenceScore: 0.59,
    status: "UNDER_REVIEW",
    occurredAt: "2026-04-02T11:25:00.000Z",
    location: locations.eastleigh,
    notes:
      "Still early. Team requested a second on-the-ground confirmation before broadening public alert.",
    audit: [
      {
        id: "audit-lead-008-1",
        at: "2026-04-02T11:45:00.000Z",
        actor: "Grace Wanjiku",
        action: "Lead queued",
        details: "Volunteer follow-up scheduled for nearby corridor.",
      },
    ],
  },
];

export const demoNotifications: DemoNotification[] = [
  {
    id: "notif-001",
    title: "Escalated lead for Amina Hassan",
    body:
      "Westlands image lead reached manual-review threshold and needs owner acknowledgement.",
    href: "/dashboard/cases/case-amina-hassan",
    read: false,
    createdAt: "2026-04-15T08:10:00.000Z",
  },
  {
    id: "notif-002",
    title: "New monitoring hit for Daniel Mwangi",
    body: "High-confidence ferry-stage post added to review queue.",
    href: "/dashboard/monitoring",
    read: false,
    createdAt: "2026-04-15T06:30:00.000Z",
  },
  {
    id: "notif-003",
    title: "Faith Atieno lead approved",
    body: "Kakamega stage search radius expanded after moderator review.",
    href: "/dashboard/tips",
    read: true,
    createdAt: "2026-04-14T16:00:00.000Z",
  },
  {
    id: "notif-004",
    title: "Kelvin Kiptoo monitoring terms updated",
    body: "Route watchlist now includes Nakuru transport channels.",
    href: "/dashboard/monitoring",
    read: true,
    createdAt: "2026-04-14T09:35:00.000Z",
  },
  {
    id: "notif-005",
    title: "Ruth Njeri case archived to family records",
    body:
      "Case poster and timeline remain available in the dashboard for audit history.",
    href: "/dashboard/cases/case-ruth-njeri",
    read: true,
    createdAt: "2026-04-13T11:20:00.000Z",
  },
];

export const demoLocations = Object.values(locations);
